import ms from 'ms';

export default {
  ACCESS_TOKEN_EXPIRE_TIME: ms('15m'),
  REFRESH_TOKEN_EXPIRE_TIME: ms('24h'),
  EMAIL_VERIFICATION_TOKEN_EXPIRE_TIME: ms('30m'),
  PASSWORD_RESET_TOKEN_EXPIRE_TIME: ms('30m'),
};
